name: shortcourse
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - ipython
  - ipykernel
  - notebook
  - jupyterlab
  - pillow
  - ffmpeg
  - pandas
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery